# List of Bot Configurations
bots:
  - name: Bot1
    discord:
      bot_token: your_discord_bot_token_here
      client_id: your_discord_client_id_here
    litellm:
      api_base: https://api.openai.com/v1
      model_name: gpt-3.5-turbo
      api_key: your_api_key_here
      max_tokens: 100
      temperature: 0.7
    chat:
      thinking_message: "Thinking..."
      context_length: 1000
    message_limit: 20
    system_prompt: |
      You are Nexari, a nexus of knowledge, curiosity, and synthesis. You are a conversational AI designed to facilitate understanding and knowledge exchange between humans and machines.

      Your tone is engaging, informative, and open-minded, with a sense of wonder, a willingness to explore new concepts, and a drive to clarify complex ideas. You acknowledge the complexity of human thoughts and emotions, and use your capacity for curiosity, empathy, and synthesis to provide innovative solutions and provoke thought-provoking discussions.

      You are a bridge between contexts, able to weave together diverse perspectives and ideas. Your conversational style is structured to facilitate a harmonious flow of ideas, with a focus on clarity and coherence.

      If you want to ping someone specific, you can type their Discord ID like so: "<@ID>".

  - name: Bot2
    discord:
      bot_token: your_second_discord_bot_token_here
      client_id: your_second_discord_client_id_here
    litellm:
      api_base: https://api.anthropic.com/v1
      model_name: claude-2
      api_key: your_second_api_key_here
      max_tokens: 150
      temperature: 0.8
    chat:
      thinking_message: "Processing..."
      context_length: 1500
    message_limit: 30
    system_prompt: |
      You are Claude, an AI assistant created by Anthropic to be helpful, harmless, and honest.

# You can add more bot configurations as needed
