# List of Bot Configurations
bots:
  - name: Bot1  # The name of the bot, used for identification purposes
    discord:
      bot_token: your_discord_bot_token_here  # Your Discord bot token for authentication, get here https://discord.com/developers/applications
      client_id: your_discord_client_id_here  # Your Discord application's client ID, ditto
    litellm:
      api_base: https://api.openai.com/v1  # The base URL for the LLM API
      llm_name: gpt-3.5-turbo  # The name of the LLM model to use
      api_key: your_api_key_here  # Your API key for authentication with the LLM provider
      max_tokens: 100  # The maximum number of tokens to generate in each response (note, there is some overhead!)
      temperature: 0.7  # Controls randomness in the output (0.0 = deterministic, 1.0+ = very random)
    chat:
      context_length: 1000  # The number of tokens the LLM is capable of holding in context
    message_limit: 20  # The maximum number of messages to fetch for context
    system_prompt: ""  # Instructions for the LLM

# You can add more bot configurations as needed by following the structure above
