bot_token: your_discord_bot_token_here  # Your Discord bot token for authentication, get here https://discord.com/developers/applications
client_id: your_discord_client_id_here
database_url: "postgresql+asyncpg://user:password@host:port/dbname"  # Database connection string
