version: '3.8'

services:
  test-db:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: test_db
    ports:
      - "9876:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  tests:
    build: .
    command: poetry run pytest tests/ -v --cov=src --cov-report=html --cov-report=term
    depends_on:
      test-db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:postgres@test-db:9876/test_db
