"""Alter check constraint on message

Revision ID: 091536e0bd7a
Revises: 140d9f5227dc
Create Date: 2024-09-27 19:34:01.937623

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '091536e0bd7a'
down_revision: Union[str, None] = '140d9f5227dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
