"""Add simulator_channel_id to Guild model

Revision ID: 140d9f5227dc
Revises: b06562575ad4
Create Date: 2024-09-27 17:42:48.628492

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '140d9f5227dc'
down_revision: Union[str, None] = 'b06562575ad4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guild', sa.Column('simulator_channel_id', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('guild', 'simulator_channel_id')
    # ### end Alembic commands ###
