"""Add last_responder to Channel model

Revision ID: 223d8d6c2306
Revises: b83f39732e94
Create Date: 2024-09-05 03:41:31.998838

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '223d8d6c2306'
down_revision: Union[str, None] = 'b83f39732e94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('channel', sa.Column('last_responder_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'channel', 'llm', ['last_responder_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'channel', type_='foreignkey')
    op.drop_column('channel', 'last_responder_id')
    # ### end Alembic commands ###
