"""Remove context_length from LLM model

Revision ID: 22d6e5a84153
Revises: 96cf46bdb0c4
Create Date: 2024-10-03 15:58:18.155364

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22d6e5a84153'
down_revision: Union[str, None] = '96cf46bdb0c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('llm', 'context_length')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('llm', sa.Column('context_length', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
