"""Add avatar column

Revision ID: 8225e015e328
Revises: d30377cc0647
Create Date: 2024-09-01 01:50:18.132275

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8225e015e328"
down_revision: Union[str, None] = "d30377cc0647"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("llm", sa.Column("avatar", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("llm", "avatar")
    # ### end Alembic commands ###
