"""Make channel_id non-nullable

Revision ID: 96cf46bdb0c4
Revises: 9228082c3eb0
Create Date: 2024-09-30 19:58:27.060688

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96cf46bdb0c4'
down_revision: Union[str, None] = '9228082c3eb0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('message', 'channel_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('message', 'channel_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    # ### end Alembic commands ###
