"""init

Revision ID: 9dc8de884731
Revises: 
Create Date: 2024-08-29 00:53:08.763331

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9dc8de884731'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('channel',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('llm',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('api_base', sa.Text(), nullable=False),
    sa.Column('llm_name', sa.Text(), nullable=False),
    sa.Column('api_key', sa.Text(), nullable=False),
    sa.Column('max_tokens', sa.Integer(), nullable=False),
    sa.Column('system_prompt', sa.Text(), nullable=True),
    sa.Column('context_length', sa.Integer(), nullable=False),
    sa.Column('message_limit', sa.Integer(), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('top_p', sa.Float(), nullable=True),
    sa.Column('top_k', sa.Integer(), nullable=True),
    sa.Column('frequency_penalty', sa.Float(), nullable=True),
    sa.Column('presence_penalty', sa.Float(), nullable=True),
    sa.Column('repetition_penalty', sa.Float(), nullable=True),
    sa.Column('min_p', sa.Float(), nullable=True),
    sa.Column('top_a', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_llm_name'), 'llm', ['name'], unique=True)
    op.create_table('webhook',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('token', sa.Text(), nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('llm_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channel.id'], ),
    sa.ForeignKeyConstraint(['llm_id'], ['llm.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('webhook')
    op.drop_index(op.f('ix_llm_name'), table_name='llm')
    op.drop_table('llm')
    op.drop_table('channel')
    # ### end Alembic commands ###
