"""Remove llm webhook relationship

Revision ID: bc628dd8622a
Revises: 22d6e5a84153
Create Date: 2024-10-22 01:53:02.687891

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc628dd8622a'
down_revision: Union[str, None] = '22d6e5a84153'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('channel', sa.Column('scanned_up_to', sa.TIMESTAMP(timezone=True), nullable=True))
    op.add_column('llm', sa.Column('avatar_url', sa.Text(), nullable=True))
    op.drop_column('llm', 'avatar')
    op.add_column('message', sa.Column('llm_id', sa.BigInteger(), nullable=True))
    op.drop_constraint('message_webhook_id_fkey', 'message', type_='foreignkey')
    op.create_foreign_key(None, 'message', 'llm', ['llm_id'], ['id'])

    # Copy llm_id over to new row
    op.execute("""
        UPDATE message
        SET llm_id=subquery.llm_id
        FROM (
            SELECT m.id as message_id, l.id as llm_id
            FROM message m INNER JOIN webhook w on m.webhook_id = w.id INNER JOIN llm l on w.llm_id = l.id
        ) as subquery
        WHERE message.id=subquery.message_id
    """)

    op.drop_column('message', 'webhook_id')
    op.drop_constraint('webhook_llm_id_fkey', 'webhook', type_='foreignkey')
    op.drop_column('webhook', 'llm_id')

    # Deduplicate webhooks, keeping one per channel
    op.execute("""
        DELETE FROM webhook
        WHERE id IN (
            SELECT id
            FROM (
                SELECT id,
                       ROW_NUMBER() OVER (PARTITION BY channel_id ORDER BY id) as rnum
                FROM webhook
            ) t
            WHERE t.rnum > 1
        )
    """)

    # Add unique_channel constraint to webhook table
    op.create_unique_constraint('unique_channel', 'webhook', ['channel_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_channel', 'webhook', type_='unique')
    op.add_column('webhook', sa.Column('llm_id', sa.BIGINT(), autoincrement=False, nullable=False))
    op.create_foreign_key('webhook_llm_id_fkey', 'webhook', 'llm', ['llm_id'], ['id'])
    op.add_column('message', sa.Column('webhook_id', sa.BIGINT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'message', type_='foreignkey')
    op.create_foreign_key('message_webhook_id_fkey', 'message', 'webhook', ['webhook_id'], ['id'])
    op.drop_column('message', 'llm_id')
    op.add_column('llm', sa.Column('avatar', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('llm', 'avatar_url')
    op.drop_column('channel', 'scanned_up_to')
    # ### end Alembic commands ###
