"""Init

Revision ID: c3daf9e5f3b7
Revises: 
Create Date: 2024-10-03 19:49:22.456404

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3daf9e5f3b7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guild',
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('discriminator', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('llm',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('api_base', sa.Text(), nullable=False),
    sa.Column('llm_name', sa.Text(), nullable=False),
    sa.Column('api_key', sa.Text(), nullable=False),
    sa.Column('max_tokens', sa.Integer(), nullable=False),
    sa.Column('system_prompt', sa.Text(), nullable=True),
    sa.Column('context_length', sa.Integer(), nullable=False),
    sa.Column('message_limit', sa.Integer(), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('top_p', sa.Float(), nullable=True),
    sa.Column('top_k', sa.Integer(), nullable=True),
    sa.Column('frequency_penalty', sa.Float(), nullable=True),
    sa.Column('presence_penalty', sa.Float(), nullable=True),
    sa.Column('repetition_penalty', sa.Float(), nullable=True),
    sa.Column('min_p', sa.Float(), nullable=True),
    sa.Column('top_a', sa.Float(), nullable=True),
    sa.Column('avatar', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['guild_id'], ['guild.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'guild_id', name='uq_name_guild_id')
    )
    op.create_index(op.f('ix_llm_name'), 'llm', ['name'], unique=False)
    op.create_table('channel',
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('last_responder_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['guild_id'], ['guild.id'], ),
    sa.ForeignKeyConstraint(['last_responder_id'], ['llm.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('webhook',
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('token', sa.Text(), nullable=False),
    sa.Column('channel_id', sa.BigInteger(), nullable=False),
    sa.Column('llm_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channel.id'], ),
    sa.ForeignKeyConstraint(['llm_id'], ['llm.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('message',
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('webhook_id', sa.BigInteger(), nullable=True),
    sa.Column('channel_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('(user_id IS NULL) != (webhook_id IS NULL)', name='user_xor_webhook'),
    sa.ForeignKeyConstraint(['channel_id'], ['channel.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['webhook_id'], ['webhook.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('message')
    op.drop_table('webhook')
    op.drop_table('channel')
    op.drop_index(op.f('ix_llm_name'), table_name='llm')
    op.drop_table('llm')
    op.drop_table('user')
    op.drop_table('guild')
    # ### end Alembic commands ###
