"""Add llm.enabled

Revision ID: d5b145054756
Revises: a335bb5c826e
Create Date: 2024-09-28 06:50:28.577315

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5b145054756'
down_revision: Union[str, None] = 'a335bb5c826e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('llm', sa.Column('enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('llm', 'enabled')
    # ### end Alembic commands ###
