"""Add from_webhook

Revision ID: f6b6babbb2af
Revises: bc628dd8622a
Create Date: 2024-10-22 14:23:00.789498

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6b6babbb2af'
down_revision: Union[str, None] = 'bc628dd8622a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('from_webhook', sa.Boolean(), server_default=sa.text('false'), nullable=False))

    # Rescan all messages
    op.execute("""
    UPDATE channel
    SET scanned_up_to = null
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('message', 'from_webhook')
    # ### end Alembic commands ###
