"""Add names and add thread support

Revision ID: f9f9e93e0ead
Revises: d5b145054756
Create Date: 2024-09-30 19:20:55.579912

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f9f9e93e0ead"
down_revision: Union[str, None] = "d5b145054756"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("channel", sa.Column("name", sa.String(), nullable=True))
    op.add_column("channel", sa.Column("parent_id", sa.BigInteger(), nullable=True))
    op.drop_constraint("channel_last_responder_id_fkey", "channel", type_="foreignkey")
    op.create_foreign_key(None, "channel", "channel", ["parent_id"], ["id"])
    op.drop_column("channel", "last_responder_id")
    op.add_column("guild", sa.Column("name", sa.String(), nullable=True))
    op.alter_column("message", "channel_id", existing_type=sa.BIGINT(), nullable=True)
    op.create_index(
        "channel_message_idx", "message", ["channel_id", "created_at"], unique=False
    )
    op.drop_column("user", "discriminator")
    op.add_column("webhook", sa.Column("name", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("webhook", "name")
    op.add_column(
        "user",
        sa.Column("discriminator", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.drop_index("channel_message_idx", table_name="message")
    op.alter_column("message", "channel_id", existing_type=sa.BIGINT(), nullable=False)
    op.drop_column("guild", "name")
    op.add_column(
        "channel",
        sa.Column("last_responder_id", sa.BIGINT(), autoincrement=False, nullable=True),
    )
    op.drop_constraint(None, "channel", type_="foreignkey")
    op.create_foreign_key(
        "channel_last_responder_id_fkey",
        "channel",
        "llm",
        ["last_responder_id"],
        ["id"],
    )
    op.drop_column("channel", "parent_id")
    op.drop_column("channel", "name")
    # ### end Alembic commands ###
