apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: discord-bot-network-policy
spec:
  podSelector:
    matchLabels:
      app: discord-bot
  policyTypes:
  - Ingress
  - Egress
  ingress:
  # Allow inbound HTTPS traffic to container port 8080 (health checks)
  - ports:
    - port: 8080  # Container/pod port
      protocol: TCP
  egress:
  # Allow Discord WebSocket and HTTPS API connections
  - to:
    - ipBlock:
        cidr: 0.0.0.0/0
    ports:
    - port: 443
      protocol: TCP
  # Allow DNS resolution
  - to:
    ports:
    - port: 53
      protocol: UDP
    - port: 53
      protocol: TCP
  # Allow Cloud SQL
  - to:
    - ipBlock:
        cidr: 0.0.0.0/0
    ports:
    - port: 5432
      protocol: TCP
