name: CI/CD

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  terraform:
    if: |
      github.event_name == 'workflow_dispatch' ||
      github.ref == 'refs/heads/main' && github.event_name == 'push' ||
      github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./terraform
    steps:
      - uses: actions/checkout@v4

      - name: Google Auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Extract Project ID and Service Account
        id: project
        run: |
          echo "PROJECT_ID=$(echo '${{ secrets.GCP_SA_KEY }}' | jq -r '.project_id')" >> $GITHUB_OUTPUT
          echo "SERVICE_ACCOUNT=$(echo '${{ secrets.GCP_SA_KEY }}' | jq -r '.client_email')" >> $GITHUB_OUTPUT

      - name: Terraform Plan
        env:
          TF_VAR_project_id: ${{ steps.project.outputs.PROJECT_ID }}
          TF_VAR_ci_service_account: ${{ steps.project.outputs.SERVICE_ACCOUNT }}
          TF_VAR_discord_token: ${{ secrets.DISCORD_TOKEN }}
          TF_VAR_discord_client_id: ${{ secrets.DISCORD_CLIENT_ID }}
        run: terraform plan -out=tfplan

      - name: Upload Terraform Plan
        uses: actions/upload-artifact@v4
        with:
          name: tfplan
          path: terraform/tfplan
          retention-days: 1

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push' && !failure()
        env:
          TF_VAR_project_id: ${{ steps.project.outputs.PROJECT_ID }}
          TF_VAR_ci_service_account: ${{ steps.project.outputs.SERVICE_ACCOUNT }}
          TF_VAR_discord_token: ${{ secrets.DISCORD_TOKEN }}
          TF_VAR_discord_client_id: ${{ secrets.DISCORD_CLIENT_ID }}
        run: |
          terraform apply tfplan

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Google Auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker for GCR
        run: gcloud auth configure-docker

      - name: Extract Project ID
        id: project
        run: |
          echo "PROJECT_ID=$(echo '${{ secrets.GCP_SA_KEY }}' | jq -r '.project_id')" >> $GITHUB_OUTPUT

      - name: Build and Push Docker images
        run: |
          # Build and push production image
          docker build --target production -t gcr.io/${{ steps.project.outputs.PROJECT_ID }}/nexari:${{ github.sha }} .
          docker push gcr.io/${{ steps.project.outputs.PROJECT_ID }}/nexari:${{ github.sha }}

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run tests with coverage
        run: |
          docker compose up --exit-code-from tests tests
        env:
          PYTEST_ADDOPTS: "--cov=src --cov-report=term-missing --cov-report=html"

      - name: Copy coverage from container
        run: |
          container_id=$(docker ps -aq -f name=tests)
          docker cp $container_id:/app/htmlcov ./htmlcov

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: coverage-report
          path: htmlcov/
          retention-days: 14

  deploy:
    needs: [ test, terraform, build ]
    if: |
      github.ref == 'refs/heads/main' && 
      github.event_name == 'push' &&
      (needs.terraform.result == 'success' || needs.terraform.result == 'skipped')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Google Auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker for GCR
        run: gcloud auth configure-docker

      - name: Extract Project ID
        id: project
        run: |
          echo "PROJECT_ID=$(echo '${{ secrets.GCP_SA_KEY }}' | jq -r '.project_id')" >> $GITHUB_OUTPUT

      - name: Get GKE credentials
        uses: google-github-actions/get-gke-credentials@v1
        with:
          cluster_name: nexari-cluster
          location: us-central1

      - name: Check for pending migrations
        id: check-migrations
        run: |
          HAS_MIGRATIONS=$(docker run \
            -e DATABASE_URL="$(gcloud secrets versions access latest --secret='database-url')" \
            gcr.io/${{ steps.project.outputs.PROJECT_ID }}/nexari:${{ github.sha }} \
            poetry run alembic current 2>/dev/null | poetry run alembic heads 2>/dev/null | diff - - >/dev/null 2>&1; echo $?)
          echo "has_migrations=$HAS_MIGRATIONS" >> $GITHUB_OUTPUT

      - name: Scale down deployment for migrations
        if: steps.check-migrations.outputs.has_migrations != '0'
        run: |
          kubectl scale deployment discord-bot --replicas=0
          # Wait for pods to terminate
          kubectl wait --for=delete pod -l app=discord-bot --timeout=60s

      - name: Run database migrations
        id: migrations
        if: steps.check-migrations.outputs.has_migrations != '0'
        continue-on-error: true
        run: |
          docker run \
            -e DATABASE_URL="$(gcloud secrets versions access latest --secret='database-url')" \
            gcr.io/${{ steps.project.outputs.PROJECT_ID }}/nexari:${{ github.sha }} \
            poetry run alembic upgrade head

      - name: Create Kubernetes Secrets
        run: |
          # Fetch secrets from Secret Manager
          DATABASE_URL=$(gcloud secrets versions access latest --secret='database-url')
          DATABASE_CONNECTION=$(gcloud secrets versions access latest --secret='database-connection')
          DISCORD_TOKEN=$(gcloud secrets versions access latest --secret='discord-token')
          DISCORD_CLIENT_ID=$(gcloud secrets versions access latest --secret='discord-client-id')
          
          # Create or update Kubernetes secret
          kubectl create secret generic bot-secrets \
            --from-literal=database-url="$DATABASE_URL" \
            --from-literal=database-connection="$DATABASE_CONNECTION" \
            --from-literal=discord-token="$DISCORD_TOKEN" \
            --from-literal=discord-client-id="$DISCORD_CLIENT_ID" \
            --dry-run=client -o yaml | kubectl apply -f -

      - name: Deploy to GKE
        id: deploy
        run: |
          # Apply Kubernetes configurations
          export bot_service_account_email=$(gcloud iam service-accounts list --filter="displayName:Workload Service Account for nexari" --format="value(email)")
          envsubst < kubernetes/serviceaccount.yaml | kubectl apply -f -
          kubectl apply -f kubernetes/network-policies.yaml
          
          # Replace variables and apply deployment
          export project_id=${{ steps.project.outputs.PROJECT_ID }}
          envsubst < kubernetes/deployment.yaml | kubectl apply -f -
          
          # Store current tag for potential rollback (if deployment exists)
          if kubectl get deployment discord-bot &>/dev/null; then
            CURRENT_TAG=$(kubectl get deployment discord-bot -o=jsonpath='{.spec.template.spec.containers[0].image}' | cut -d ':' -f2)
            echo "current_tag=$CURRENT_TAG" >> $GITHUB_OUTPUT
          fi

          # Update deployment with new image
          kubectl set image deployment/discord-bot discord-bot=gcr.io/${{ steps.project.outputs.PROJECT_ID }}/nexari:${{ github.sha }}
          
          # Scale back up if was scaled down for migrations
          kubectl scale deployment discord-bot --replicas=1

          # Wait for rollout to complete
          if ! kubectl rollout status deployment/discord-bot --timeout=300s; then
            echo "::error::Deployment failed to roll out"
            exit 1
          fi

      - name: Rollback on failure
        if: failure()
        run: |
          echo "Deployment failed. Rolling back..."
          PREVIOUS_TAG="${{ steps.deploy.outputs.current_tag }}"
          if [ -n "$PREVIOUS_TAG" ]; then
            kubectl set image deployment/discord-bot discord-bot=gcr.io/${{ steps.project.outputs.PROJECT_ID }}/nexari:$PREVIOUS_TAG
            kubectl rollout undo deployment/discord-bot
            echo "Rolled back to $PREVIOUS_TAG"
          else
            echo "No previous tag found to roll back to"
          fi
          exit 1

      - name: Tag and push latest on success
        if: steps.deploy.outcome == 'success'
        run: |
          docker pull gcr.io/${{ steps.project.outputs.PROJECT_ID }}/nexari:${{ github.sha }}
          docker tag gcr.io/${{ steps.project.outputs.PROJECT_ID }}/nexari:${{ github.sha }} gcr.io/${{ steps.project.outputs.PROJECT_ID }}/nexari:latest
          docker push gcr.io/${{ steps.project.outputs.PROJECT_ID }}/nexari:latest
          echo "Deployment successful!"
