name: 'Build and Deploy'

on:
  workflow_run:
    workflows: ['Terraform']
    types:
      - completed
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - uses: actions/checkout@v4

    - name: Google Auth
      uses: google-github-actions/auth@v2
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2

    - name: Configure Docker for GCR
      run: gcloud auth configure-docker

    - name: Build Docker image
      run: docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/nexari:${{ github.sha }} .

    - name: Push Docker image
      run: |
        docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/nexari:${{ github.sha }}
        docker tag gcr.io/${{ secrets.GCP_PROJECT_ID }}/nexari:${{ github.sha }} gcr.io/${{ secrets.GCP_PROJECT_ID }}/nexari:latest
        docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/nexari:latest

    - name: Deploy to Cloud Run
      uses: google-github-actions/deploy-cloudrun@v2
      with:
        service: nexari
        image: gcr.io/${{ secrets.GCP_PROJECT_ID }}/nexari:${{ github.sha }}
        region: us-central1
