name: 'Build and Deploy'

on:
  workflow_run:
    workflows: ['Terraform']
    types:
      - completed
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - uses: actions/checkout@v4

    - name: Google Auth
      uses: google-github-actions/auth@v2
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2

    - name: Configure Docker for GCR
      run: gcloud auth configure-docker

    - name: Extract Project ID
      id: project
      run: |
        echo "PROJECT_ID=$(echo '${{ secrets.GCP_SA_KEY }}' | jq -r '.project_id')" >> $GITHUB_OUTPUT

    - name: Build Docker image
      run: docker build -t gcr.io/${{ steps.project.outputs.PROJECT_ID }}/nexari:${{ github.sha }} .

    - name: Push Docker image
      run: |
        # Always push the SHA-tagged image
        docker push gcr.io/${{ steps.project.outputs.PROJECT_ID }}/nexari:${{ github.sha }}
        
        # Only tag and push :latest if this is the head of main
        if [[ "${{ github.ref }}" == "refs/heads/main" && "${{ github.event.workflow_run.head_sha }}" == "${{ github.sha }}" ]]; then
          docker tag gcr.io/${{ steps.project.outputs.PROJECT_ID }}/nexari:${{ github.sha }} gcr.io/${{ steps.project.outputs.PROJECT_ID }}/nexari:latest
          docker push gcr.io/${{ steps.project.outputs.PROJECT_ID }}/nexari:latest
        fi

    - name: Deploy to Cloud Run
      uses: google-github-actions/deploy-cloudrun@v2
      with:
        service: nexari
        image: gcr.io/${{ secrets.GCP_PROJECT_ID }}/nexari:${{ github.sha }}
        region: us-central1
